version: "3.8"

networks:
  webnet:
    driver: overlay
    attachable: true # Needed in order to run custom commands in the container

services:
  db:
    image: postgres:11.10-alpine
    env_file:
      - docker.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webnet
  app:
    image: njausteve/njausteve:772f6907d08ffb6aae40017d6cd4df53ee24b4c8
    env_file:
      - docker.env
    volumes:
      - certdata:/opt/app/site_encrypt_db
    ports:
      - "80:4000"
      - "443:4001"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

volumes:
  pgdata:
  certdata:
